# Generated by Django 4.2.2 on 2023-10-25 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_usermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='name',
            new_name='email',
        ),
    ]
